name: Logger
version: ${project.version}
main: me.prism3.logger.Main
api-version: 1.13
authors: [ Prism3, thelooter, Sidna ]
description: Log all Activities from Players and Server Side!
softdepend: [Essentials, AuthMe, Vault, PlaceholderAPI, LiteBans, AdvancedBan, PlaceholderAPI, Geyser, Floodgate, ViaVersion, WorldGuard]
commands:
  logger:
    description: "PluginUpdater command."
  logger reload:
    description: "Reloads the PluginUpdater configs."
  logger dump:
    description: "Creates an online pastebin url of the plugin's config and discord."
  logger discord:
    description: "Display the discord support server link."
  logger playerinventory:
    description: "Opens a menu with all online players and their available backups."
  logger toggle:
    description: "Toggle spy features ON/OFF."
  loggerget:
    description: "Get player messages"
permissions:
  logger.staff:
    description: "Allows the Player to execute PluginUpdater Commands, spy on others actions, and view PluginUpdater Updates."
    children:
      logger.reload: true
      logger.spy: true
      logger.update: true
  logger.exempt:
    description: "Prevents the Player from getting logged."
    children:
      logger.exempt.discord: true
  logger.exempt.discord:
    description: "Prevents the Player from getting discord logged."
  logger.reload:
    description: "Allows to Reload the PluginUpdater."
    default: op
  logger.spy:
    description: "Ability to see other players' and Staff's actions."
    default: op
  logger.spy.bypass:
    description: "Ability to see other players and staff's Actions but others can not."
    default: op
  logger.staff.log:
    description: "Logs Staff Members."
    default: op
    children:
      logger.exempt: false
  logger.update:
    description: "Ability to receive PluginUpdater Updates."
    default: op