# /////////////////////////////////////////////////////////////
# /                                                           /
# /                      Logger Plugin                        /
# /                                                           /
# /                    [ Proxy Version ]                      /
# /                                                           /
# /////////////////////////////////////////////////////////////
#
# Thank you for using Logger Plugin! If you are experiencing any issues
# or have any suggestions / features you want to be implemented into the plugin
# feel free to join the support Discord Server!
#
# Spigot: Prism3
# Discord: Prism3#9371 | ID: 403667971089760257
# Discord Server: https://discord.gg/MfR5mcpVfX
#
# Config.1.8


# Server Name
Server-Name: "Server_Name"

# Date & Time Formatter
Time-Formatter: "yyyy-MM-dd HH:mm:ss"

# How many Days for the logs to be deleted
# Set it to -1 to cancel the Deletion
File-Deletion: 7

# Log to Files
Log-to-Files: true

# This will log players with the "loggerproxy.staff.log" permission node in their own folder / file
Staff:
  Enabled: false

# Logging features
Log-Player:
  Chat: true
  Commands: true
  Login: true
  Leave: true
  Server-Switch: true

Log-Server:
  Reload: true
  Start: true
  Stop: true
  RAM: true

Log-Extras:
  LiteBans: true
  PAF: true

# Player-Commands features
Player-Commands:
  Whitelist-Commands: false
  Commands-to-Log:
    - /server
    - /lookup
  Blacklist-Commands: true
  Commands-to-Block:
    - /login
    - /register
    - /msg

# Enable to show Player's IPs
Player-Login:
  Player-IP: false

# Server RAM
# How often should we check for the Proxy's RAM
# It's better to have it above 1 min to avoid any complications
# Value in Ticks, 20 Ticks = 1 Second
# Percent goes from 0 -> 100
RAM:
  Checker: 6000
  Percent: 50

# LiteBans Features to Log
# It does not log revoked actions!
# example: unban <player>
LiteBans:
  IP-Ban: true
  Temp-IP-Ban: true
  Ban: true
  Temp-Ban: true
  Mute: true
  Temp-Mute: true
  Kick: true

# External Database Feature
# Available Types are MySQL and MariaDB
# Data-Deletion Value in Days, Set it -1 to cancel
Database:
  Enable: false
  Type: MySQL
  Host: localhost
  Port: 3306
  Username: username
  Password: PassworD
  Database: database
  Data-Deletion: 7

# SQLite Feature
# Data-Deletion Value in Days, Set it -1 to cancel
SQLite:
  Enable: false
  Data-Deletion: 7

# Checks for Updates
Update-Checker: true