name: Logger
version: ${project.version}
main: com.carpour.logger.Main
api-version: 1.13
authors: [ Prism3 , thelooter ]
description: Log all Activities from Players and Server Side!
softdepend: [Essentials , AuthMe]
commands:
  logger:
    description: Plugin command.
  logger reload:
    description: "Reloads the plugin configs."
  logger credits:
    description: "Shows the plugin authors."
permissions:
  logger.staff:
    description: "Allows the user to view Plugin Updates."
    default: op
    children:
      logger.exempt: true
      logger.reload: true
      logger.spy: true
      logger.update: true
  logger.exempt:
    description: "Prevents the Player from Getting Logged."
    default: op
  logger.reload:
    description: "Allows to Reload the Plugin."
    default: op
  logger.spy:
    description: "Ability to see other player's and Staff's Actions."
    default: op
  logger.spy.bypass:
    description: "Ability to see other player's and staff's Actions but others can not."
    default: op
    children:
      logger.spy: true
  logger.staff.log:
    description: "Logs Staff Members."
    children:
      logger.exempt: false
  logger.update:
    description: "Update Message is sent to the Users with this Permission."
    default: op