<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>logger</artifactId>
        <groupId>me.prism3</groupId>
        <version>1.8.4</version>
    </parent>

    <artifactId>logger-paper</artifactId>

    <packaging>jar</packaging>

    <name>Logger Universal</name>
    <description>Universal All-in-One JAR for Spigot, Paper, Purpur, BungeeCord, Waterfall, and Velocity</description>

    <properties>
        <java.version>${paper.java.version}</java.version> <!-- Override to 17 -->
    </properties>

    <build>

        <defaultGoal>clean package</defaultGoal>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

        <plugins>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.11.0</version>
                <executions>
                    <execution>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>update-property</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <property>project.version</property>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <minimizeJar>false</minimizeJar>
                            <relocations>
                                <relocation>
                                    <pattern>com.zaxxer.hikari</pattern>
                                    <shadedPattern>me.prism3.logger.libs.hikari</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.mariadb.jdbc</pattern>
                                    <shadedPattern>me.prism3.logger.libs.mariadb</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.postgresql</pattern>
                                    <shadedPattern>me.prism3.logger.libs.postgresql</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.github.cdimascio.dotenv</pattern>
                                    <shadedPattern>me.prism3.logger.libs.dotenv</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.github.benmanes.caffeine</pattern>
                                    <shadedPattern>me.prism3.logger.libs.caffeine</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.destroystokyo.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.16.5-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>me.prism3</groupId>
            <artifactId>logger-spigot</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>me.prism3</groupId>
            <artifactId>logger-v1_21</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>me.prism3</groupId>
            <artifactId>logger-bungee</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>me.prism3</groupId>
            <artifactId>logger-velocity</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
